fishingapp/fishingapp/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from homepage import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    re_path(r'^', include('homepage.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fishingapp/homepage/urls.py
from django.urls import re_path, path
from homepage import views

app_name='homepage'

urlpatterns = [
    re_path(r'^register/$', views.register, name='register'),
    re_path(r'^orderplaced/$', views.orderplaced, name='orderplaced'),
    re_path(r'^logout/$', views.user_logout, name='logout'),
    re_path(r'^login/$', views.user_login, name='user_login'),
    re_path(r'^(?P<pk>\d+)/$',views.ItemDetailView.as_view(),name='detail'),
    re_path(r'^cart/$',views.cart,name='cart'),
    re_path(r'^checkout/$',views.checkout,name='checkout'),
    re_path(r'^update_item/$',views.updateItem,name='update_item'),
    re_path(r'^$', views.index, name='index'),
]

fishingapp/homepage/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class Item(models.Model):
    name = models.CharField(max_length=256)
    description = models.CharField(max_length=2000)
    price = models.DecimalField(decimal_places=2,max_digits=10)
    image = models.ImageField(upload_to='products/')

    def __str__(self):
        return self.name

class Order(models.Model):
    date_ordered = models.DateTimeField(auto_now_add=True)
    transaction_id = models.CharField(max_length=100, null=True)

    def __str__(self):
        return(self.id)

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total

class OrderItem(models.Model):
    item = models.ForeignKey(Item, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.item.price * self.quantity
        return total

fishingapp/homepage/forms.py
from django import forms
from django.contrib.auth.models import User
from homepage.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

fishingapp/homepage/views.py
from django.shortcuts import render
from homepage.forms import UserForm
from django.http import JsonResponse
import json

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from homepage import models
from django.views.generic import View, TemplateView, ListView, DetailView

def orderplaced(request):
    context = {'cartitems':0}
    return render(request, 'homepage/orderplaced.html', context)

def index(request):
    item_list = models.Item.objects.all()
    order, created = models.Order.objects.get_or_create()
    items = order.orderitem_set.all()
    cartitems = order.get_cart_items

    return render(request, 'homepage/item_list.html',{'item_list':item_list,'cartitems':cartitems})

# Create your views here.
class ItemDetailView(DetailView):
    context_object_name = 'item_detail'
    model = models.Item
    template_name = 'homepage/item.html'

    order, created = models.Order.objects.get_or_create()
    items = order.orderitem_set.all()
    cartitems = order.get_cart_items
    extra_context={'cartitems': cartitems}

# def itemDetails(request, pk):
#     item_detail = models.Item.objects.all()
#     return render(request,'homepage/item.html',{'item_detail':item_detail})

def updateItem(request):
    data = json.loads(request.body)
    productid = data['productid']
    action = data['action']

    print('action',action)
    print('productid',productid)

    product = models.Item.objects.get(id=productid)
    order, created = models.Order.objects.get_or_create()
    orderItem, created = models.OrderItem.objects.get_or_create(order=order, item=product)

    if action == 'add':
        orderItem.quantity = orderItem.quantity + 1
    elif action == 'remove':
        orderItem.quantity = orderItem.quantity - 1

    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()

    return JsonResponse('Item was added', safe=False)

def cart(request):
    order, created = models.Order.objects.get_or_create()
    items = order.orderitem_set.all()
    cartitems = order.get_cart_items
    context = {'items':items, 'order':order, 'cartitems':cartitems}
    return render(request, 'homepage/cart.html', context)

def checkout(request):
    order, created = models.Order.objects.get_or_create()
    items = order.orderitem_set.all()
    cartitems = order.get_cart_items
    context = {'items':items, 'order':order, 'cartitems':cartitems}
    return render(request, 'homepage/checkout.html', context)

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)

        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
        else:
            print(user_form.errors)
    else:
        user_form = UserForm()

    return render(request, 'homepage/registration.html',
                                        {'user_form':user_form,
                                        'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            return HttpResponse("invalid login details supplied")
    else:
        return render(request,'homepage/login.html',{})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

fishingapp/homepage/templates/homepage/cart.html
{% extends "homepage/homepage_base.html" %}
{% load static %}
{% block body_block %}
<div class="row">
<div class="col-lg-12">
  <div class="box-element">

    <a  class="btn btn-outline-dark" href="{% url 'homepage:index' %}">&#x2190; Continue Shopping</a>

    <br>
    <br>
    <table class="table">
      <tr>
        <th><h5>Items: <strong>{{order.get_cart_items}}</strong></h5></th>
        <th><h5>Total:<strong> €{{order.get_cart_total}}</strong></h5></th>
        <th>
          <a  style="float:right; margin:5px;" class="btn btn-success" href="{% url 'homepage:checkout' %}">Checkout</a>
        </th>
      </tr>
    </table>

  </div>

  <br>
  <div class="box-element">
    <div class="cart-row">
      <div style="flex:2"></div>
      <div style="flex:2"><strong>Item</strong></div>
      <div style="flex:1"><strong>Price</strong></div>
      <div style="flex:1"><strong>Quantity</strong></div>
      <div style="flex:1"><strong>Total</strong></div>
    </div>

    {% for item in items %}
    <div class="cart-row">
      <div style="flex:2"><img class="row-image" src="{{item.item.image.url}}"></div>
      <div style="flex:2"><p>{{item.item.name}}</p></div>
      <div style="flex:1"><p>€{{item.item.price|floatformat:2}}</p></div>
      <div style="flex:1">
        <p class="quantity">{{item.quantity}}</p>
        <div class="quantity">
          <img data-product={{item.item.id}} data-action="add" class="chg-quantity update-cart" src="{% static  'images/arrow-up.png' %}">

          <img data-product={{item.item.id}} data-action="remove" class="chg-quantity update-cart" src="{% static  'images/arrow-down.png' %}">
        </div>
      </div>
      <div style="flex:1"><p>€{{item.get_total}}</p></div>
    </div>
    {% endfor %}

  </div>
</div>
</div>
{% endblock %}

fishingapp/homepage/templates/homepage/checkout.html
{% extends "homepage/homepage_base.html" %}
{% load static %}
{% block body_block %}
<div class="row">
<div class="col-lg-6">
  <div class="box-element" id="form-wrapper">
    <form id="form" action="{% url 'homepage:orderplaced' %}">
      <div id="user-info">
        <div class="form-field">
          <input required class="form-control" type="text" name="name" placeholder="Name..">
        </div>
        <div class="form-field">
          <input required class="form-control" type="email" name="email" placeholder="Email..">
        </div>
      </div>

      <div id="shipping-info">
        <hr>
        <p>Shipping Information:</p>
        <hr>
        <div class="form-field">
          <input class="form-control" type="text" name="address" placeholder="Address..">
        </div>
        <div class="form-field">
          <input class="form-control" type="text" name="city" placeholder="City..">
        </div>
        <div class="form-field">
          <input class="form-control" type="text" name="state" placeholder="State..">
        </div>
        <div class="form-field">
          <input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
        </div>
        <div class="form-field">
          <input class="form-control" type="text" name="country" placeholder="Zip code..">
        </div>
      </div>

      <hr>
      <input id="form-button" class="btn btn-success btn-block" type="submit" value="Place Order">
    </form>
  </div>

  <br>
  <div class="box-element hidden" id="payment-info">
    <small>Paypal Options</small>
  </div>

</div>

<div class="col-lg-6">
  <div class="box-element">
    <a  class="btn btn-outline-dark" href="{% url 'homepage:cart' %}">&#x2190; Back to Cart</a>
    <hr>
    <h3>Order Summary</h3>
    <hr>
    {% for item in items %}
    <div class="cart-row">
      <div style="flex:2"><img class="row-image" src="{{item.item.image.url}}"></div>
      <div style="flex:2"><p>{{item.item.name}}</p></div>
      <div style="flex:1"><p>{{item.item.price}}</p></div>
      <div style="flex:1"><p>{{item.quantity}}</p></div>
    </div>
    {% endfor %}

    <h5>Items:   {{order.get_cart_items}}</h5>
    <h5>Total:   €{{order.get_cart_total|floatformat:2}}</h5>
  </div>
</div>
</div>
{% endblock %}

fishingapp/homepage/templates/homepage/homepage_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Fishing Goods</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/styles.css" %}">

    <script type="text/javascript">
    function getCookie(name) {
      let cookieValue = null;
      if (document.cookie && document.cookie !== '') {
          const cookies = document.cookie.split(';');
          for (let i = 0; i < cookies.length; i++) {
              const cookie = cookies[i].trim();
              // Does this cookie string begin with the name we want?
              if (cookie.substring(0, name.length + 1) === (name + '=')) {
                  cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                  break;
              }
          }
      }
      return cookieValue;
    }
    const csrftoken = getCookie('csrftoken');
    </script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
	  <a class="navbar-brand" href="{% url 'homepage:index' %}">BAITANDCATCH.lv</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item active">
	      </li>

	    </ul>
	    <div class="form-inline my-2 my-lg-0">
	     	<a href="{% url 'admin:index' %}"class="btn btn-warning">Login</a>

	     	<a href="{% url 'homepage:cart' %}">
	    		<img  id="cart-icon" src="{% static 'images/cart.png' %}">
	    	</a>
	    	<p id="cart-total">{{cartitems}}</p>

	    </div>

	  </div>
	</nav>
    </div>
<div class="container">
  {% block body_block %}
  {% endblock %}
</div>

<script type="text/javascript" src="{% static 'js/cart.js' %}"> </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

fishingapp/homepage/templates/homepage/item.html
{% extends "homepage/homepage_base.html" %}
{% block body_block %}
  <div class="box-element">
    <div class="row">
    <div class="col-lg-6">
    <img class="itemdetailimage" src="{{item_detail.image.url}}" alt="">

    </div>
      <div class="col-lg-6 itemdetails">

          <h2>{{item_detail.name}}</h2>
          <p>{{item_detail.description}}</p>
          <h3 id="descprice">€{{item_detail.price}}</h3>
          <button data-product={{item_detail.id}} data-action="add" class="btn btn-outline-success add-btn update-cart">Add to Cart</button>
      </div>
    </div>
    </div>


{% endblock %}

fishingapp/homepage/templates/homepage/item_list.html
{% extends "homepage/homepage_base.html" %}
{% load static %}
{% block body_block %}


    <div class="row">

    {% for item in item_list %}
      <div class="col">
        <div class="product box-element">
        <a href="{{item.id}}"><img class="imgrid" src="{{item.image.url}}" alt=""></a>
        <!-- <button type="button" class="addc btn btn-warning">Add to Cart</button> -->
        <h6><strong>{{item.name}}</strong></h6>
      		<hr>

      		<button data-product={{item.id}} data-action="add" class="btn btn-outline-success add-btn update-cart">Add to Cart</button>
      		<h4 style="display: inline-block; float: right"><strong>€{{item.price}}</strong>
        </div>
      </div>

    {% endfor %}
    </div>


{% endblock %}

fishingapp/homepage/templates/homepage/login.html
{% extends "homepage/homepage_base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'homepage:user_login' %}" method="post">
      {% csrf_token %}
      <label for="username">Username:</label>
      <input type="text" name="username" placeholder="Enter Username">
      <label for="password">Password:</label>
      <input type="password" name="password">
      <input type="submit" name="" value="Login">
    </form>

  </div>
{% endblock %}

fishingapp/homepage/templates/homepage/orderplaced.html
{% extends "homepage/homepage_base.html" %}
{% block body_block %}


<div id="thankyoubox" class="box-element">
<h3>Thank you! </h3>
<h5>Your order was placed successfully. Please click <a href="{% url 'homepage:index' %}">here</a> to go to the home page</h5>
</div>

{% endblock %}

fishingapp/homepage/templates/homepage/registration.html
{% extends "homepage/homepage_base.html" %}
{% load static %}

{% block body_block %}
  <div class="jumbotron">
    {% if registered %}
    <h1>Thank you for registering!</h1>
    {% else %}
    <h1>Register here!</h1>
    <h3>Please fill out the form</h3>

    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{user_form.as_p}}
      <input type="submit" name="" value="Register">
    </form>
    {% endif %}
  </div>
{% endblock %}

fishingapp/templates/homepage/login.html
{% extends 'homepage/base.html' %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'homepage:user_login' %}" method="post">
      {% csrf_token %}
      <label for="username">Username:</label>
      <input type="text" name="username" placeholder="Enter Username">
      <label for="password">Password:</label>
      <input type="password" name="password">
      <input type="submit" name="" value="Login">
    </form>

  </div>
{% endblock %}

fishingapp/templates/homepage/registration.html
{% extends 'homepage/base.html' %}
{% load static %}

{% block body_block %}
  <div class="jumbotron">
    {% if registered %}
    <h1>Thank you for registering!</h1>
    {% else %}
    <h1>Register here!</h1>
    <h3>Please fill out the form</h3>

    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{user_form.as_p}}
      <input type="submit" name="" value="Register">
    </form>
    {% endif %}
  </div>
{% endblock %}